spring.datasource.url=jdbc:postgresql://localhost:5432/avocat_platform
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# Configuration Ollama (IA locale)
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3

# Desactiver security pour les tests (optionnel)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration