# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/avocat_platform
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
server.port=8080

# JWT
app.jwt.secret=avocat_secret_key_super_longue_minimum_256_bits_12345678901234567890
app.jwt.expiration=86400000

# Configuration SMTP pour Hazem
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=somranihazem1@gmail.com

# VOTRE CODE GÉNÉRÉ (sans les espaces)
spring.mail.password=wblnnsbeomhvltgp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Augmenter la taille maximale des fichiers (ex: 10 Mo)
# Indispensable pour l'upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ============================================================
# Monitoring - Actuator + Prometheus
# ============================================================
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=when-authorized
management.metrics.tags.application=avocat-pro-backend

# Necessaire pour obtenir les percentiles (p50, p95) sur tes futurs
# compteurs custom chatbot et OCR
management.metrics.distribution.percentiles-histogram.chatbot.latence=true
management.metrics.distribution.percentiles-histogram.ocr.traitement.latence=true
management.metrics.distribution.percentiles.chatbot.latence=0.5,0.95,0.99
management.metrics.distribution.percentiles.ocr.traitement.latence=0.5,0.95,0.99
management.metrics.distribution.percentiles-histogram.http.server.requests=true